2025-06-04 15:16:13,937 - root - INFO - [c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network] Manifest loaded: {'description': 'AI application that can generate an image given a detailed text prompt as an input. Example: Wide angle camera shot of a cat sitting on a beach wearing a superman costume, highly realistic, high quality', 'dev': False, 'dos': 'https://dos.openfabric.network/', 'input': 'dc8f06af066e4a7880a5938933236037/60ea27dd30eda09645d03c7bc75bb5cc/1.0', 'name': 'Image-Generator', 'organization': None, 'output': 'dc8f06af066e4a7880a5938933236037/f08eab03688219ff07bde0f30b95ccdb/1.0', 'overview': None, 'sdk': '0.2.33', 'version': '1.0.0'}
2025-06-04 15:16:14,416 - root - INFO - [c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network] Input schema loaded: {'$ref': '#/definitions/SdInputSchema', '$schema': 'http://json-schema.org/draft-07/schema#', 'definitions': {'SdInputSchema': {'additionalProperties': False, 'properties': {'prompt': {'description': "The text prompt for the image to be generated. It should not exceed 60 words. Example: 'Wide angle camera shot of a cat sitting on a beach wearing a superman costume, highly realistic, high quality'", 'title': 'prompt', 'type': 'string'}}, 'type': 'object'}}}
2025-06-04 15:16:14,867 - root - INFO - [c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network] Output schema loaded: {'$ref': '#/definitions/SdOutputSchema', '$schema': 'http://json-schema.org/draft-07/schema#', 'definitions': {'SdOutputSchema': {'additionalProperties': False, 'properties': {'result': {'description': 'The generated image output file', 'is_resource': True, 'resource_encoding': 'blob', 'resource_type': 'data', 'title': 'result', 'type': ['string', 'null']}}, 'type': 'object'}}}
2025-06-04 15:16:14,867 - root - INFO - c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network-proxy: Proxy started
2025-06-04 15:16:14,867 - root - INFO - c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network-proxy: State checker started
2025-06-04 15:16:15,475 - root - INFO - [c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network] Connection established.
2025-06-04 15:16:15,972 - root - INFO - [f0b5f319156c4819b9827000b17e511a.node3.openfabric.network] Manifest loaded: {'description': 'AI application that can generate a 3D model of a single image given as input. For a 3D model generated, it can output either a video file, or the GLB object file, or both (based on output_type given in config, default is both).', 'dev': False, 'dos': 'https://dos.openfabric.network/', 'input': 'dc8f06af066e4a7880a5938933236037/e4ceecf1c5a4c22c03e45cc23ec72888/1.0', 'name': 'Image-to-3D', 'organization': None, 'output': 'dc8f06af066e4a7880a5938933236037/627d7d9a27410ddbeedbbe920ad34568/1.0', 'overview': None, 'sdk': '0.2.33', 'version': '0.1'}
2025-06-04 15:16:16,436 - root - INFO - [f0b5f319156c4819b9827000b17e511a.node3.openfabric.network] Input schema loaded: {'$ref': '#/definitions/ModelInputSchema', '$schema': 'http://json-schema.org/draft-07/schema#', 'definitions': {'ModelInputSchema': {'additionalProperties': False, 'properties': {'input_image': {'description': 'A single input image (.jpeg, .jpg, or .png only) of which the 3D model should be generated. Background will be automatically removed from the input image.', 'title': 'input_image', 'type': 'string'}}, 'required': ['input_image'], 'type': 'object'}}}
2025-06-04 15:16:16,819 - root - INFO - [f0b5f319156c4819b9827000b17e511a.node3.openfabric.network] Output schema loaded: {'$ref': '#/definitions/ModelOutputSchema', '$schema': 'http://json-schema.org/draft-07/schema#', 'definitions': {'ModelOutputSchema': {'additionalProperties': False, 'properties': {'generated_object': {'description': 'The .glb resource file of the generated 3D model', 'is_resource': True, 'resource_encoding': 'WebGL', 'resource_type': 'data', 'title': 'generated_object', 'type': ['string', 'null']}, 'video_object': {'description': 'A 4-second video showing the 3D model generated by the application, rotating and viewed from different angles.', 'title': 'video_object', 'type': ['string', 'null']}}, 'type': 'object'}}}
2025-06-04 15:16:16,819 - root - INFO - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Proxy started
2025-06-04 15:16:16,819 - root - INFO - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: State checker started
2025-06-04 15:16:17,427 - root - INFO - [f0b5f319156c4819b9827000b17e511a.node3.openfabric.network] Connection established.
2025-06-04 15:18:55,522 - root - INFO - [c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network] Manifest loaded: {'description': 'AI application that can generate an image given a detailed text prompt as an input. Example: Wide angle camera shot of a cat sitting on a beach wearing a superman costume, highly realistic, high quality', 'dev': False, 'dos': 'https://dos.openfabric.network/', 'input': 'dc8f06af066e4a7880a5938933236037/60ea27dd30eda09645d03c7bc75bb5cc/1.0', 'name': 'Image-Generator', 'organization': None, 'output': 'dc8f06af066e4a7880a5938933236037/f08eab03688219ff07bde0f30b95ccdb/1.0', 'overview': None, 'sdk': '0.2.33', 'version': '1.0.0'}
2025-06-04 15:18:55,996 - root - INFO - [c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network] Input schema loaded: {'$ref': '#/definitions/SdInputSchema', '$schema': 'http://json-schema.org/draft-07/schema#', 'definitions': {'SdInputSchema': {'additionalProperties': False, 'properties': {'prompt': {'description': "The text prompt for the image to be generated. It should not exceed 60 words. Example: 'Wide angle camera shot of a cat sitting on a beach wearing a superman costume, highly realistic, high quality'", 'title': 'prompt', 'type': 'string'}}, 'type': 'object'}}}
2025-06-04 15:18:56,435 - root - INFO - [c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network] Output schema loaded: {'$ref': '#/definitions/SdOutputSchema', '$schema': 'http://json-schema.org/draft-07/schema#', 'definitions': {'SdOutputSchema': {'additionalProperties': False, 'properties': {'result': {'description': 'The generated image output file', 'is_resource': True, 'resource_encoding': 'blob', 'resource_type': 'data', 'title': 'result', 'type': ['string', 'null']}}, 'type': 'object'}}}
2025-06-04 15:18:56,439 - root - INFO - c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network-proxy: Proxy started
2025-06-04 15:18:56,439 - root - INFO - c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network-proxy: State checker started
2025-06-04 15:18:57,045 - root - INFO - [c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network] Connection established.
2025-06-04 15:18:57,468 - root - INFO - [f0b5f319156c4819b9827000b17e511a.node3.openfabric.network] Manifest loaded: {'description': 'AI application that can generate a 3D model of a single image given as input. For a 3D model generated, it can output either a video file, or the GLB object file, or both (based on output_type given in config, default is both).', 'dev': False, 'dos': 'https://dos.openfabric.network/', 'input': 'dc8f06af066e4a7880a5938933236037/e4ceecf1c5a4c22c03e45cc23ec72888/1.0', 'name': 'Image-to-3D', 'organization': None, 'output': 'dc8f06af066e4a7880a5938933236037/627d7d9a27410ddbeedbbe920ad34568/1.0', 'overview': None, 'sdk': '0.2.33', 'version': '0.1'}
2025-06-04 15:18:57,921 - root - INFO - [f0b5f319156c4819b9827000b17e511a.node3.openfabric.network] Input schema loaded: {'$ref': '#/definitions/ModelInputSchema', '$schema': 'http://json-schema.org/draft-07/schema#', 'definitions': {'ModelInputSchema': {'additionalProperties': False, 'properties': {'input_image': {'description': 'A single input image (.jpeg, .jpg, or .png only) of which the 3D model should be generated. Background will be automatically removed from the input image.', 'title': 'input_image', 'type': 'string'}}, 'required': ['input_image'], 'type': 'object'}}}
2025-06-04 15:18:58,356 - root - INFO - [f0b5f319156c4819b9827000b17e511a.node3.openfabric.network] Output schema loaded: {'$ref': '#/definitions/ModelOutputSchema', '$schema': 'http://json-schema.org/draft-07/schema#', 'definitions': {'ModelOutputSchema': {'additionalProperties': False, 'properties': {'generated_object': {'description': 'The .glb resource file of the generated 3D model', 'is_resource': True, 'resource_encoding': 'WebGL', 'resource_type': 'data', 'title': 'generated_object', 'type': ['string', 'null']}, 'video_object': {'description': 'A 4-second video showing the 3D model generated by the application, rotating and viewed from different angles.', 'title': 'video_object', 'type': ['string', 'null']}}, 'type': 'object'}}}
2025-06-04 15:18:58,356 - root - INFO - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Proxy started
2025-06-04 15:18:58,367 - root - INFO - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: State checker started
2025-06-04 15:18:59,073 - root - INFO - [f0b5f319156c4819b9827000b17e511a.node3.openfabric.network] Connection established.
2025-06-04 15:19:34,974 - root - ERROR - Error generating LLM response: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/generate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019EBB9F6410>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-06-04 15:19:34,983 - root - INFO - Created rid87aa78c44b1f4bba8f835652c72e92f8
2025-06-04 15:19:38,617 - sdk - WARNING - [93mResource not found: data_blob_adea20124b4a71282164ed8cf8925ec456a7153d35fc46a7a04e9695d7313f8c/executions/8c832e20ac25498f9f2a81e582b1be99[0m
2025-06-04 15:19:49,163 - root - INFO - Created ridd8922cb206224c3092659e137f038983
2025-06-04 15:20:21,469 - sdk - WARNING - [93mResource not found: data_WebGL_0e6a061f2296af4b9e31978e7d11953dd366e9fc2aa9f208c0b1a06841f4cb2d/executions/ce24501f10b64c32adb7b1d639149430[0m
2025-06-04 15:37:26,150 - root - INFO - [c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network] Manifest loaded: {'description': 'AI application that can generate an image given a detailed text prompt as an input. Example: Wide angle camera shot of a cat sitting on a beach wearing a superman costume, highly realistic, high quality', 'dev': False, 'dos': 'https://dos.openfabric.network/', 'input': 'dc8f06af066e4a7880a5938933236037/60ea27dd30eda09645d03c7bc75bb5cc/1.0', 'name': 'Image-Generator', 'organization': None, 'output': 'dc8f06af066e4a7880a5938933236037/f08eab03688219ff07bde0f30b95ccdb/1.0', 'overview': None, 'sdk': '0.2.33', 'version': '1.0.0'}
2025-06-04 15:37:26,616 - root - INFO - [c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network] Input schema loaded: {'$ref': '#/definitions/SdInputSchema', '$schema': 'http://json-schema.org/draft-07/schema#', 'definitions': {'SdInputSchema': {'additionalProperties': False, 'properties': {'prompt': {'description': "The text prompt for the image to be generated. It should not exceed 60 words. Example: 'Wide angle camera shot of a cat sitting on a beach wearing a superman costume, highly realistic, high quality'", 'title': 'prompt', 'type': 'string'}}, 'type': 'object'}}}
2025-06-04 15:37:27,050 - root - INFO - [c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network] Output schema loaded: {'$ref': '#/definitions/SdOutputSchema', '$schema': 'http://json-schema.org/draft-07/schema#', 'definitions': {'SdOutputSchema': {'additionalProperties': False, 'properties': {'result': {'description': 'The generated image output file', 'is_resource': True, 'resource_encoding': 'blob', 'resource_type': 'data', 'title': 'result', 'type': ['string', 'null']}}, 'type': 'object'}}}
2025-06-04 15:37:27,050 - root - INFO - c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network-proxy: Proxy started
2025-06-04 15:37:27,050 - root - INFO - c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network-proxy: State checker started
2025-06-04 15:37:27,667 - root - INFO - [c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network] Connection established.
2025-06-04 15:37:28,116 - root - INFO - [f0b5f319156c4819b9827000b17e511a.node3.openfabric.network] Manifest loaded: {'description': 'AI application that can generate a 3D model of a single image given as input. For a 3D model generated, it can output either a video file, or the GLB object file, or both (based on output_type given in config, default is both).', 'dev': False, 'dos': 'https://dos.openfabric.network/', 'input': 'dc8f06af066e4a7880a5938933236037/e4ceecf1c5a4c22c03e45cc23ec72888/1.0', 'name': 'Image-to-3D', 'organization': None, 'output': 'dc8f06af066e4a7880a5938933236037/627d7d9a27410ddbeedbbe920ad34568/1.0', 'overview': None, 'sdk': '0.2.33', 'version': '0.1'}
2025-06-04 15:37:28,598 - root - INFO - [f0b5f319156c4819b9827000b17e511a.node3.openfabric.network] Input schema loaded: {'$ref': '#/definitions/ModelInputSchema', '$schema': 'http://json-schema.org/draft-07/schema#', 'definitions': {'ModelInputSchema': {'additionalProperties': False, 'properties': {'input_image': {'description': 'A single input image (.jpeg, .jpg, or .png only) of which the 3D model should be generated. Background will be automatically removed from the input image.', 'title': 'input_image', 'type': 'string'}}, 'required': ['input_image'], 'type': 'object'}}}
2025-06-04 15:37:29,048 - root - INFO - [f0b5f319156c4819b9827000b17e511a.node3.openfabric.network] Output schema loaded: {'$ref': '#/definitions/ModelOutputSchema', '$schema': 'http://json-schema.org/draft-07/schema#', 'definitions': {'ModelOutputSchema': {'additionalProperties': False, 'properties': {'generated_object': {'description': 'The .glb resource file of the generated 3D model', 'is_resource': True, 'resource_encoding': 'WebGL', 'resource_type': 'data', 'title': 'generated_object', 'type': ['string', 'null']}, 'video_object': {'description': 'A 4-second video showing the 3D model generated by the application, rotating and viewed from different angles.', 'title': 'video_object', 'type': ['string', 'null']}}, 'type': 'object'}}}
2025-06-04 15:37:29,049 - root - INFO - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Proxy started
2025-06-04 15:37:29,049 - root - INFO - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: State checker started
2025-06-04 15:37:29,656 - root - INFO - [f0b5f319156c4819b9827000b17e511a.node3.openfabric.network] Connection established.
2025-06-04 15:38:20,907 - root - INFO - [c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network] Manifest loaded: {'description': 'AI application that can generate an image given a detailed text prompt as an input. Example: Wide angle camera shot of a cat sitting on a beach wearing a superman costume, highly realistic, high quality', 'dev': False, 'dos': 'https://dos.openfabric.network/', 'input': 'dc8f06af066e4a7880a5938933236037/60ea27dd30eda09645d03c7bc75bb5cc/1.0', 'name': 'Image-Generator', 'organization': None, 'output': 'dc8f06af066e4a7880a5938933236037/f08eab03688219ff07bde0f30b95ccdb/1.0', 'overview': None, 'sdk': '0.2.33', 'version': '1.0.0'}
2025-06-04 15:38:21,347 - root - INFO - [c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network] Input schema loaded: {'$ref': '#/definitions/SdInputSchema', '$schema': 'http://json-schema.org/draft-07/schema#', 'definitions': {'SdInputSchema': {'additionalProperties': False, 'properties': {'prompt': {'description': "The text prompt for the image to be generated. It should not exceed 60 words. Example: 'Wide angle camera shot of a cat sitting on a beach wearing a superman costume, highly realistic, high quality'", 'title': 'prompt', 'type': 'string'}}, 'type': 'object'}}}
2025-06-04 15:38:21,806 - root - INFO - [c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network] Output schema loaded: {'$ref': '#/definitions/SdOutputSchema', '$schema': 'http://json-schema.org/draft-07/schema#', 'definitions': {'SdOutputSchema': {'additionalProperties': False, 'properties': {'result': {'description': 'The generated image output file', 'is_resource': True, 'resource_encoding': 'blob', 'resource_type': 'data', 'title': 'result', 'type': ['string', 'null']}}, 'type': 'object'}}}
2025-06-04 15:38:21,806 - root - INFO - c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network-proxy: Proxy started
2025-06-04 15:38:21,806 - root - INFO - c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network-proxy: State checker started
2025-06-04 15:38:22,412 - root - INFO - [c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network] Connection established.
2025-06-04 15:38:22,837 - root - INFO - [f0b5f319156c4819b9827000b17e511a.node3.openfabric.network] Manifest loaded: {'description': 'AI application that can generate a 3D model of a single image given as input. For a 3D model generated, it can output either a video file, or the GLB object file, or both (based on output_type given in config, default is both).', 'dev': False, 'dos': 'https://dos.openfabric.network/', 'input': 'dc8f06af066e4a7880a5938933236037/e4ceecf1c5a4c22c03e45cc23ec72888/1.0', 'name': 'Image-to-3D', 'organization': None, 'output': 'dc8f06af066e4a7880a5938933236037/627d7d9a27410ddbeedbbe920ad34568/1.0', 'overview': None, 'sdk': '0.2.33', 'version': '0.1'}
2025-06-04 15:38:23,254 - root - INFO - [f0b5f319156c4819b9827000b17e511a.node3.openfabric.network] Input schema loaded: {'$ref': '#/definitions/ModelInputSchema', '$schema': 'http://json-schema.org/draft-07/schema#', 'definitions': {'ModelInputSchema': {'additionalProperties': False, 'properties': {'input_image': {'description': 'A single input image (.jpeg, .jpg, or .png only) of which the 3D model should be generated. Background will be automatically removed from the input image.', 'title': 'input_image', 'type': 'string'}}, 'required': ['input_image'], 'type': 'object'}}}
2025-06-04 15:38:23,720 - root - INFO - [f0b5f319156c4819b9827000b17e511a.node3.openfabric.network] Output schema loaded: {'$ref': '#/definitions/ModelOutputSchema', '$schema': 'http://json-schema.org/draft-07/schema#', 'definitions': {'ModelOutputSchema': {'additionalProperties': False, 'properties': {'generated_object': {'description': 'The .glb resource file of the generated 3D model', 'is_resource': True, 'resource_encoding': 'WebGL', 'resource_type': 'data', 'title': 'generated_object', 'type': ['string', 'null']}, 'video_object': {'description': 'A 4-second video showing the 3D model generated by the application, rotating and viewed from different angles.', 'title': 'video_object', 'type': ['string', 'null']}}, 'type': 'object'}}}
2025-06-04 15:38:23,720 - root - INFO - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Proxy started
2025-06-04 15:38:23,720 - root - INFO - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: State checker started
2025-06-04 15:38:25,204 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 168, in connect
    raise exceptions.ConnectionError(
socketio.exceptions.ConnectionError: One or more namespaces failed to connect
2025-06-04 15:38:25,937 - root - INFO - [f0b5f319156c4819b9827000b17e511a.node3.openfabric.network] Connection established.
2025-06-04 15:38:40,293 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 120, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
2025-06-04 15:38:55,383 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 120, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
2025-06-04 15:39:10,487 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 120, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
2025-06-04 15:39:25,565 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 120, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
2025-06-04 15:39:40,639 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 120, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
2025-06-04 15:39:55,708 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 120, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
2025-06-04 15:40:10,791 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 120, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
2025-06-04 15:40:25,878 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 120, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
2025-06-04 15:40:40,956 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 120, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
2025-06-04 15:40:56,030 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 120, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
2025-06-04 15:41:11,105 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 120, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
2025-06-04 15:41:26,183 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 120, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
2025-06-04 15:41:41,267 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 120, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
2025-06-04 15:41:56,348 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 120, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
2025-06-04 15:42:11,447 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 120, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
2025-06-04 15:42:26,564 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 120, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
2025-06-04 15:42:41,630 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 120, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
2025-06-04 15:42:56,699 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 120, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
2025-06-04 15:43:11,767 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 120, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
2025-06-04 15:43:26,858 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 120, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
2025-06-04 15:43:41,956 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 120, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
2025-06-04 15:43:57,032 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 120, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
2025-06-04 15:44:12,101 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 120, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
2025-06-04 15:44:27,172 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 120, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
2025-06-04 15:44:42,251 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 120, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
2025-06-04 15:44:57,325 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 120, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
2025-06-04 15:45:12,389 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 120, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
2025-06-04 15:45:27,458 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 120, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
2025-06-04 15:45:42,527 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 120, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
2025-06-04 15:45:57,623 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 120, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
2025-06-04 15:46:12,687 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 120, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
2025-06-04 15:46:27,762 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 120, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
2025-06-04 15:46:42,844 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 120, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
2025-06-04 15:46:57,920 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 120, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
2025-06-04 15:47:12,998 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 120, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
2025-06-04 15:47:28,076 - root - ERROR - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Could not connect to server. Retrying in 15 seconds to wss://f0b5f319156c4819b9827000b17e511a.node3.openfabric.network/app
Traceback (most recent call last):
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\openfabric_pysdk\helper\proxy.py", line 233, in __run
    self.__sio.connect(self.__url, transports='websocket', namespaces=["/app"])
  File "C:\Users\mrunm\Downloads\3d-modeling-openfabric-main\3d-modeling-openfabric-main\venv\Lib\site-packages\socketio\client.py", line 120, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
2025-06-04 15:48:15,164 - root - INFO - [c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network] Manifest loaded: {'description': 'AI application that can generate an image given a detailed text prompt as an input. Example: Wide angle camera shot of a cat sitting on a beach wearing a superman costume, highly realistic, high quality', 'dev': False, 'dos': 'https://dos.openfabric.network/', 'input': 'dc8f06af066e4a7880a5938933236037/60ea27dd30eda09645d03c7bc75bb5cc/1.0', 'name': 'Image-Generator', 'organization': None, 'output': 'dc8f06af066e4a7880a5938933236037/f08eab03688219ff07bde0f30b95ccdb/1.0', 'overview': None, 'sdk': '0.2.33', 'version': '1.0.0'}
2025-06-04 15:48:15,577 - root - INFO - [c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network] Input schema loaded: {'$ref': '#/definitions/SdInputSchema', '$schema': 'http://json-schema.org/draft-07/schema#', 'definitions': {'SdInputSchema': {'additionalProperties': False, 'properties': {'prompt': {'description': "The text prompt for the image to be generated. It should not exceed 60 words. Example: 'Wide angle camera shot of a cat sitting on a beach wearing a superman costume, highly realistic, high quality'", 'title': 'prompt', 'type': 'string'}}, 'type': 'object'}}}
2025-06-04 15:48:16,028 - root - INFO - [c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network] Output schema loaded: {'$ref': '#/definitions/SdOutputSchema', '$schema': 'http://json-schema.org/draft-07/schema#', 'definitions': {'SdOutputSchema': {'additionalProperties': False, 'properties': {'result': {'description': 'The generated image output file', 'is_resource': True, 'resource_encoding': 'blob', 'resource_type': 'data', 'title': 'result', 'type': ['string', 'null']}}, 'type': 'object'}}}
2025-06-04 15:48:16,028 - root - INFO - c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network-proxy: Proxy started
2025-06-04 15:48:16,028 - root - INFO - c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network-proxy: State checker started
2025-06-04 15:48:16,638 - root - INFO - [c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network] Connection established.
2025-06-04 15:48:17,162 - root - INFO - [f0b5f319156c4819b9827000b17e511a.node3.openfabric.network] Manifest loaded: {'description': 'AI application that can generate a 3D model of a single image given as input. For a 3D model generated, it can output either a video file, or the GLB object file, or both (based on output_type given in config, default is both).', 'dev': False, 'dos': 'https://dos.openfabric.network/', 'input': 'dc8f06af066e4a7880a5938933236037/e4ceecf1c5a4c22c03e45cc23ec72888/1.0', 'name': 'Image-to-3D', 'organization': None, 'output': 'dc8f06af066e4a7880a5938933236037/627d7d9a27410ddbeedbbe920ad34568/1.0', 'overview': None, 'sdk': '0.2.33', 'version': '0.1'}
2025-06-04 15:48:17,617 - root - INFO - [f0b5f319156c4819b9827000b17e511a.node3.openfabric.network] Input schema loaded: {'$ref': '#/definitions/ModelInputSchema', '$schema': 'http://json-schema.org/draft-07/schema#', 'definitions': {'ModelInputSchema': {'additionalProperties': False, 'properties': {'input_image': {'description': 'A single input image (.jpeg, .jpg, or .png only) of which the 3D model should be generated. Background will be automatically removed from the input image.', 'title': 'input_image', 'type': 'string'}}, 'required': ['input_image'], 'type': 'object'}}}
2025-06-04 15:48:18,060 - root - INFO - [f0b5f319156c4819b9827000b17e511a.node3.openfabric.network] Output schema loaded: {'$ref': '#/definitions/ModelOutputSchema', '$schema': 'http://json-schema.org/draft-07/schema#', 'definitions': {'ModelOutputSchema': {'additionalProperties': False, 'properties': {'generated_object': {'description': 'The .glb resource file of the generated 3D model', 'is_resource': True, 'resource_encoding': 'WebGL', 'resource_type': 'data', 'title': 'generated_object', 'type': ['string', 'null']}, 'video_object': {'description': 'A 4-second video showing the 3D model generated by the application, rotating and viewed from different angles.', 'title': 'video_object', 'type': ['string', 'null']}}, 'type': 'object'}}}
2025-06-04 15:48:18,076 - root - INFO - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Proxy started
2025-06-04 15:48:18,077 - root - INFO - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: State checker started
2025-06-04 15:48:18,783 - root - INFO - [f0b5f319156c4819b9827000b17e511a.node3.openfabric.network] Connection established.
2025-06-04 15:53:18,880 - root - ERROR - Error generating LLM response: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/generate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000221B2426210>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-06-04 15:53:18,880 - root - INFO - Created rid0492fbdbcbed471faeeee90d49d52522
2025-06-04 15:53:38,109 - root - ERROR - Error generating LLM response: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/generate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000221B2B3F010>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-06-04 15:53:38,109 - root - INFO - Created rideb2433df80b94dd289566b4a7ca2843b
2025-06-04 15:53:41,942 - sdk - WARNING - [93mResource not found: data_blob_cdf82cff31796fa62d1e7b5b1e174df35da9a298eb49f6a707885d49c87a4b7f/executions/4f144f357ee74708a1583f9a8ecf81a2[0m
2025-06-04 15:53:47,840 - root - INFO - Created rid9c061353b03443078c628b37ce846abb
2025-06-04 15:54:18,167 - sdk - WARNING - [93mResource not found: data_WebGL_d85939adfe1beb375aa1e2a0389e7056db18a9734bf08f478179abc2b02f2a71/executions/544e6cd7277641bbb68c40df47674226[0m
2025-06-04 15:56:26,240 - root - INFO - Removed empty directory: outputs/images
2025-06-04 15:56:26,240 - root - INFO - Removed empty directory: outputs/models
2025-06-04 15:58:59,322 - root - INFO - [c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network] Manifest loaded: {'description': 'AI application that can generate an image given a detailed text prompt as an input. Example: Wide angle camera shot of a cat sitting on a beach wearing a superman costume, highly realistic, high quality', 'dev': False, 'dos': 'https://dos.openfabric.network/', 'input': 'dc8f06af066e4a7880a5938933236037/60ea27dd30eda09645d03c7bc75bb5cc/1.0', 'name': 'Image-Generator', 'organization': None, 'output': 'dc8f06af066e4a7880a5938933236037/f08eab03688219ff07bde0f30b95ccdb/1.0', 'overview': None, 'sdk': '0.2.33', 'version': '1.0.0'}
2025-06-04 15:58:59,758 - root - INFO - [c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network] Input schema loaded: {'$ref': '#/definitions/SdInputSchema', '$schema': 'http://json-schema.org/draft-07/schema#', 'definitions': {'SdInputSchema': {'additionalProperties': False, 'properties': {'prompt': {'description': "The text prompt for the image to be generated. It should not exceed 60 words. Example: 'Wide angle camera shot of a cat sitting on a beach wearing a superman costume, highly realistic, high quality'", 'title': 'prompt', 'type': 'string'}}, 'type': 'object'}}}
2025-06-04 15:59:00,226 - root - INFO - [c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network] Output schema loaded: {'$ref': '#/definitions/SdOutputSchema', '$schema': 'http://json-schema.org/draft-07/schema#', 'definitions': {'SdOutputSchema': {'additionalProperties': False, 'properties': {'result': {'description': 'The generated image output file', 'is_resource': True, 'resource_encoding': 'blob', 'resource_type': 'data', 'title': 'result', 'type': ['string', 'null']}}, 'type': 'object'}}}
2025-06-04 15:59:00,226 - root - INFO - c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network-proxy: Proxy started
2025-06-04 15:59:00,228 - root - INFO - c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network-proxy: State checker started
2025-06-04 15:59:00,832 - root - INFO - [c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network] Connection established.
2025-06-04 15:59:01,256 - root - INFO - [f0b5f319156c4819b9827000b17e511a.node3.openfabric.network] Manifest loaded: {'description': 'AI application that can generate a 3D model of a single image given as input. For a 3D model generated, it can output either a video file, or the GLB object file, or both (based on output_type given in config, default is both).', 'dev': False, 'dos': 'https://dos.openfabric.network/', 'input': 'dc8f06af066e4a7880a5938933236037/e4ceecf1c5a4c22c03e45cc23ec72888/1.0', 'name': 'Image-to-3D', 'organization': None, 'output': 'dc8f06af066e4a7880a5938933236037/627d7d9a27410ddbeedbbe920ad34568/1.0', 'overview': None, 'sdk': '0.2.33', 'version': '0.1'}
2025-06-04 15:59:01,706 - root - INFO - [f0b5f319156c4819b9827000b17e511a.node3.openfabric.network] Input schema loaded: {'$ref': '#/definitions/ModelInputSchema', '$schema': 'http://json-schema.org/draft-07/schema#', 'definitions': {'ModelInputSchema': {'additionalProperties': False, 'properties': {'input_image': {'description': 'A single input image (.jpeg, .jpg, or .png only) of which the 3D model should be generated. Background will be automatically removed from the input image.', 'title': 'input_image', 'type': 'string'}}, 'required': ['input_image'], 'type': 'object'}}}
2025-06-04 15:59:02,158 - root - INFO - [f0b5f319156c4819b9827000b17e511a.node3.openfabric.network] Output schema loaded: {'$ref': '#/definitions/ModelOutputSchema', '$schema': 'http://json-schema.org/draft-07/schema#', 'definitions': {'ModelOutputSchema': {'additionalProperties': False, 'properties': {'generated_object': {'description': 'The .glb resource file of the generated 3D model', 'is_resource': True, 'resource_encoding': 'WebGL', 'resource_type': 'data', 'title': 'generated_object', 'type': ['string', 'null']}, 'video_object': {'description': 'A 4-second video showing the 3D model generated by the application, rotating and viewed from different angles.', 'title': 'video_object', 'type': ['string', 'null']}}, 'type': 'object'}}}
2025-06-04 15:59:02,158 - root - INFO - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Proxy started
2025-06-04 15:59:02,158 - root - INFO - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: State checker started
2025-06-04 15:59:02,766 - root - INFO - [f0b5f319156c4819b9827000b17e511a.node3.openfabric.network] Connection established.
2025-06-04 16:02:26,520 - root - INFO - [c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network] Manifest loaded: {'description': 'AI application that can generate an image given a detailed text prompt as an input. Example: Wide angle camera shot of a cat sitting on a beach wearing a superman costume, highly realistic, high quality', 'dev': False, 'dos': 'https://dos.openfabric.network/', 'input': 'dc8f06af066e4a7880a5938933236037/60ea27dd30eda09645d03c7bc75bb5cc/1.0', 'name': 'Image-Generator', 'organization': None, 'output': 'dc8f06af066e4a7880a5938933236037/f08eab03688219ff07bde0f30b95ccdb/1.0', 'overview': None, 'sdk': '0.2.33', 'version': '1.0.0'}
2025-06-04 16:02:26,929 - root - INFO - [c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network] Input schema loaded: {'$ref': '#/definitions/SdInputSchema', '$schema': 'http://json-schema.org/draft-07/schema#', 'definitions': {'SdInputSchema': {'additionalProperties': False, 'properties': {'prompt': {'description': "The text prompt for the image to be generated. It should not exceed 60 words. Example: 'Wide angle camera shot of a cat sitting on a beach wearing a superman costume, highly realistic, high quality'", 'title': 'prompt', 'type': 'string'}}, 'type': 'object'}}}
2025-06-04 16:02:27,380 - root - INFO - [c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network] Output schema loaded: {'$ref': '#/definitions/SdOutputSchema', '$schema': 'http://json-schema.org/draft-07/schema#', 'definitions': {'SdOutputSchema': {'additionalProperties': False, 'properties': {'result': {'description': 'The generated image output file', 'is_resource': True, 'resource_encoding': 'blob', 'resource_type': 'data', 'title': 'result', 'type': ['string', 'null']}}, 'type': 'object'}}}
2025-06-04 16:02:27,380 - root - INFO - c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network-proxy: Proxy started
2025-06-04 16:02:27,380 - root - INFO - c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network-proxy: State checker started
2025-06-04 16:02:28,091 - root - INFO - [c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network] Connection established.
2025-06-04 16:02:28,696 - root - INFO - [f0b5f319156c4819b9827000b17e511a.node3.openfabric.network] Manifest loaded: {'description': 'AI application that can generate a 3D model of a single image given as input. For a 3D model generated, it can output either a video file, or the GLB object file, or both (based on output_type given in config, default is both).', 'dev': False, 'dos': 'https://dos.openfabric.network/', 'input': 'dc8f06af066e4a7880a5938933236037/e4ceecf1c5a4c22c03e45cc23ec72888/1.0', 'name': 'Image-to-3D', 'organization': None, 'output': 'dc8f06af066e4a7880a5938933236037/627d7d9a27410ddbeedbbe920ad34568/1.0', 'overview': None, 'sdk': '0.2.33', 'version': '0.1'}
2025-06-04 16:02:29,158 - root - INFO - [f0b5f319156c4819b9827000b17e511a.node3.openfabric.network] Input schema loaded: {'$ref': '#/definitions/ModelInputSchema', '$schema': 'http://json-schema.org/draft-07/schema#', 'definitions': {'ModelInputSchema': {'additionalProperties': False, 'properties': {'input_image': {'description': 'A single input image (.jpeg, .jpg, or .png only) of which the 3D model should be generated. Background will be automatically removed from the input image.', 'title': 'input_image', 'type': 'string'}}, 'required': ['input_image'], 'type': 'object'}}}
2025-06-04 16:02:29,611 - root - INFO - [f0b5f319156c4819b9827000b17e511a.node3.openfabric.network] Output schema loaded: {'$ref': '#/definitions/ModelOutputSchema', '$schema': 'http://json-schema.org/draft-07/schema#', 'definitions': {'ModelOutputSchema': {'additionalProperties': False, 'properties': {'generated_object': {'description': 'The .glb resource file of the generated 3D model', 'is_resource': True, 'resource_encoding': 'WebGL', 'resource_type': 'data', 'title': 'generated_object', 'type': ['string', 'null']}, 'video_object': {'description': 'A 4-second video showing the 3D model generated by the application, rotating and viewed from different angles.', 'title': 'video_object', 'type': ['string', 'null']}}, 'type': 'object'}}}
2025-06-04 16:02:29,611 - root - INFO - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Proxy started
2025-06-04 16:02:29,611 - root - INFO - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: State checker started
2025-06-04 16:02:30,257 - root - INFO - [f0b5f319156c4819b9827000b17e511a.node3.openfabric.network] Connection established.
2025-06-04 16:10:16,466 - root - ERROR - Error generating LLM response: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/generate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026301274C10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-06-04 16:10:16,466 - root - INFO - Created ridcbf41cf59d574cf1be6537625a79767b
2025-06-04 16:10:20,214 - sdk - WARNING - [93mResource not found: data_blob_6c0db0fbd4ee069a7d8f9f20a28d6cd7ca7215d4faa220bf4c2a66a47e5b243f/executions/84a377a023a04fec886dc8c53668b08f[0m
2025-06-04 16:11:13,319 - root - ERROR - Error generating LLM response: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/generate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000263013CC990>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-06-04 16:11:13,348 - root - INFO - Created rid44fbe477158f406585eddbb57c790618
2025-06-04 16:11:17,075 - sdk - WARNING - [93mResource not found: data_blob_6e7f7b0f49e3afbdf8ca0b4b856ccebca5bbebdd292e806231370a1d6bdbe9dc/executions/5ff611b8ca344ae185853eab02b39595[0m
2025-06-04 16:11:23,652 - root - INFO - Created ridecb6d9158c4b4e30926295e1ef5f6437
2025-06-04 16:12:11,888 - sdk - WARNING - [93mResource not found: data_WebGL_d4535e0988be197a44e9118f8826e058ac67541ffcdb8e21bcc9431b273d75de/executions/e33a0c9b2c784e478588bfe46373a36c[0m
2025-06-04 16:12:45,699 - root - ERROR - Error generating LLM response: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/generate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000263013CA4D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-06-04 16:12:45,734 - root - INFO - Created rid7e55f115a96f429bbfe2b1ee2d0b1706
2025-06-04 16:12:49,567 - sdk - WARNING - [93mResource not found: data_blob_3248a0333d4480e3b49c72b355451f267776558459713341f46bd3ddd25bc792/executions/576b94ab64644208922d948f2b947d3c[0m
2025-06-04 16:13:01,444 - root - ERROR - Error generating LLM response: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/generate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000263011ABD10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-06-04 16:13:01,472 - root - INFO - Created ridffcc9ced68c6487991502f6c4c235ccb
2025-06-04 16:13:02,447 - root - INFO - Created rid077061f060854e15981c032c877d033b
2025-06-04 16:13:05,297 - sdk - WARNING - [93mResource not found: data_blob_42e9cdddfcc4089c1a8b11283ace3790ca48863edcc48bcabc0bd13ebc6e46f5/executions/0c2c83c5951c4128926894c2d29196dd[0m
2025-06-04 16:13:08,028 - root - INFO - Created ridd249bdcb8c6f406793ee887bd97aa568
2025-06-04 16:13:19,161 - root - ERROR - Error generating LLM response: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/generate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000263011C4C10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-06-04 16:13:20,625 - root - ERROR - Error generating LLM response: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/generate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002630116A9D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-06-04 16:13:20,653 - root - INFO - Created rid6781b8c60d1f45ef8b94b3be40ec9f35
2025-06-04 16:13:24,589 - sdk - WARNING - [93mResource not found: data_blob_3af4326645cf74e8d2425b4adcc4fffa064c3d79ab5930b16d1d523a9b7c14fc/executions/4f851271d64d4521b4596a121e7cd5ca[0m
2025-06-04 16:13:39,303 - sdk - WARNING - [93mResource not found: data_WebGL_972f12f72dcca890a54b0cf1323d0edf90ee181349ce601356e963094b4a4964/executions/1705e0bc6db449f89dc4d1640ee8a640[0m
2025-06-04 16:13:45,766 - root - INFO - Created rid830f9c76f72b421fb171ad9c97cfeda6
2025-06-04 16:14:14,333 - sdk - WARNING - [93mResource not found: data_WebGL_74358dac52052324b3eec1292524553b1372bf4d53e14775b825b2f530374e1c/executions/fecb7b38020f4b77897d282803c72b52[0m
2025-06-04 16:14:41,823 - sdk - WARNING - [93mResource not found: data_WebGL_6cbd04c088f73e8793a56f2adef7bfd1fe8324a0cbef3aca97428f10816357fc/executions/867a8bb605cd45959df1785ced2a9c61[0m
2025-06-04 16:22:51,029 - root - INFO - [c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network] Manifest loaded: {'description': 'AI application that can generate an image given a detailed text prompt as an input. Example: Wide angle camera shot of a cat sitting on a beach wearing a superman costume, highly realistic, high quality', 'dev': False, 'dos': 'https://dos.openfabric.network/', 'input': 'dc8f06af066e4a7880a5938933236037/60ea27dd30eda09645d03c7bc75bb5cc/1.0', 'name': 'Image-Generator', 'organization': None, 'output': 'dc8f06af066e4a7880a5938933236037/f08eab03688219ff07bde0f30b95ccdb/1.0', 'overview': None, 'sdk': '0.2.33', 'version': '1.0.0'}
2025-06-04 16:22:51,490 - root - INFO - [c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network] Input schema loaded: {'$ref': '#/definitions/SdInputSchema', '$schema': 'http://json-schema.org/draft-07/schema#', 'definitions': {'SdInputSchema': {'additionalProperties': False, 'properties': {'prompt': {'description': "The text prompt for the image to be generated. It should not exceed 60 words. Example: 'Wide angle camera shot of a cat sitting on a beach wearing a superman costume, highly realistic, high quality'", 'title': 'prompt', 'type': 'string'}}, 'type': 'object'}}}
2025-06-04 16:22:51,888 - root - INFO - [c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network] Output schema loaded: {'$ref': '#/definitions/SdOutputSchema', '$schema': 'http://json-schema.org/draft-07/schema#', 'definitions': {'SdOutputSchema': {'additionalProperties': False, 'properties': {'result': {'description': 'The generated image output file', 'is_resource': True, 'resource_encoding': 'blob', 'resource_type': 'data', 'title': 'result', 'type': ['string', 'null']}}, 'type': 'object'}}}
2025-06-04 16:22:51,890 - root - INFO - c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network-proxy: Proxy started
2025-06-04 16:22:51,890 - root - INFO - c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network-proxy: State checker started
2025-06-04 16:22:52,495 - root - INFO - [c25dcd829d134ea98f5ae4dd311d13bc.node3.openfabric.network] Connection established.
2025-06-04 16:22:52,934 - root - INFO - [f0b5f319156c4819b9827000b17e511a.node3.openfabric.network] Manifest loaded: {'description': 'AI application that can generate a 3D model of a single image given as input. For a 3D model generated, it can output either a video file, or the GLB object file, or both (based on output_type given in config, default is both).', 'dev': False, 'dos': 'https://dos.openfabric.network/', 'input': 'dc8f06af066e4a7880a5938933236037/e4ceecf1c5a4c22c03e45cc23ec72888/1.0', 'name': 'Image-to-3D', 'organization': None, 'output': 'dc8f06af066e4a7880a5938933236037/627d7d9a27410ddbeedbbe920ad34568/1.0', 'overview': None, 'sdk': '0.2.33', 'version': '0.1'}
2025-06-04 16:22:53,390 - root - INFO - [f0b5f319156c4819b9827000b17e511a.node3.openfabric.network] Input schema loaded: {'$ref': '#/definitions/ModelInputSchema', '$schema': 'http://json-schema.org/draft-07/schema#', 'definitions': {'ModelInputSchema': {'additionalProperties': False, 'properties': {'input_image': {'description': 'A single input image (.jpeg, .jpg, or .png only) of which the 3D model should be generated. Background will be automatically removed from the input image.', 'title': 'input_image', 'type': 'string'}}, 'required': ['input_image'], 'type': 'object'}}}
2025-06-04 16:22:53,770 - root - INFO - [f0b5f319156c4819b9827000b17e511a.node3.openfabric.network] Output schema loaded: {'$ref': '#/definitions/ModelOutputSchema', '$schema': 'http://json-schema.org/draft-07/schema#', 'definitions': {'ModelOutputSchema': {'additionalProperties': False, 'properties': {'generated_object': {'description': 'The .glb resource file of the generated 3D model', 'is_resource': True, 'resource_encoding': 'WebGL', 'resource_type': 'data', 'title': 'generated_object', 'type': ['string', 'null']}, 'video_object': {'description': 'A 4-second video showing the 3D model generated by the application, rotating and viewed from different angles.', 'title': 'video_object', 'type': ['string', 'null']}}, 'type': 'object'}}}
2025-06-04 16:22:53,770 - root - INFO - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: Proxy started
2025-06-04 16:22:53,770 - root - INFO - f0b5f319156c4819b9827000b17e511a.node3.openfabric.network-proxy: State checker started
2025-06-04 16:22:54,485 - root - INFO - [f0b5f319156c4819b9827000b17e511a.node3.openfabric.network] Connection established.
